# Generated by Django 4.1.5 on 2023-01-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تایید شده'),
        ),
    ]
